### PR TITLE
working plugin for sending sms / mms for cordova

### PR DESCRIPTION
**Pull request by IgorYanchuk**

### CODE REVIEW

**Comment by Eugenizer** [comment]
Hi @dbaq! I understand it's hard to find free time, but what do you think about this pull request? May we finally get MMS support

**Comment by dbaq** [comment]
Hi everyone, sorry for the late reply.

First of all thanks for the contribution and for opening a PR.

I won't be merging this one until we figure out a few things:
- formatting (easy)
- permissions: 
IMO: it would be pretty bad to add all these extra permissions. Some developers just want to have `SEND_SMS`.
```
            <uses-permission android:name="android.permission.INTERNET"/>
            <uses-permission android:name="android.permission.SEND_SMS" />
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
```
- hardcoded stuff (i.e. `String imageFileName = "cashToSendMms.png";`). I am not sure this code has been tested thoroughly.

Thanks, again.

Best,
@dbaq

**Comment by srhyne** [comment]
@dbaq I think the text 'cashToSendMms' is throwing you off. @Agent00krosh probably meant to use 'cacheToSendSms'. It's a temp file name before reading the file I think. So it's hard coded for a reason, I think.

**Comment by ademcalhann** [comment]
merhaba  Cordoba plugin ile SMS uygulaması yazdım ama Google play yayın izini vermedi sorun Varsayılan SMS işleyici izni almak gerekli config.xml de böyle birşey yok nasıl yapacağız uygulamamız yayınlanamıyor

**Pull request closed without merging**
