### PR TITLE
Added Windows 10 Universal App Support

### PR DESCRIPTION
**Pull request by Vo2le**
Its not much code and i hope i haven't make any mistakes on upload.
Maybe i can have some feedback if someone successfully tested the code.

### CODE REVIEW

**Comment by agarrharr** [comment]
This should definitely be tested if anyone has a Windows 10 phone.

Also, one piece of feedback though, Almost every line in plugin.xml is changed (due to indentation), so it's really hard to tell what has changed in this file. Also, it didn't need to be indented because the tag at the top isn't a normal tag and it doesn't have a closing tag. Could you update your pull request?

To do this:
1. Change the file
2. Run `git commit --amend` (this will open up your text editor)
3. Save and close the file that was opened
4. Run `git push -f`

**Comment by agarrharr** [comment]
I'll leave it up to @dbaq, if he wants to merge it. I don't know if we'll be able to find anyone else to test it on a windows phone.

**Comment by dbaq** [comment]
Thanks @Vo2le for contributing and @aharris88 for reviewing. Maybe @brodybits can try before we merge this? I have no way to test that code. @brodybits, are you please available to test this code?

it is related to #31.

**Comment by brody2consult** [comment]
> @brodybits, are you please available to test this code?
> 
> it is related to #31.

@dbaq unfortunately I do not have a Windows 10 phone and am still Visual
Studio 2013 (Express). I am also really busy with commitments this week and
will probably upgrade to Visual Studio 2015 in the next 1-2 weeks.

I can try this on a Windows Phone 8.1 simulator tonight and report if it
works there or not. If it works on Windows Phone 8.1 I will recommend that
you accept this as an "alpha" or "pre-alpha" version (with a note in the
README) and let the community help with further testing.

I can also look for others who could help with Windows 10 testing.

**Comment by dbaq** [comment]
That would be great, thank you @brodybits. Keep us posted.

**Comment by brody2consult** [comment]
> That would be great, thank you @brodybits. Keep us posted.

Unfortunately I could not even run the Windows Phone 8.1 emulator for some
reason. I will probably deal with this next week. (I also want to get my
sqlite plugin working on Windows 10.)

I suggest you keep this in a branch and publish a pointer in case someone
else wants to try it out.

**Comment by dbaq** [comment]
Thanks for the quick feedback. I'll be waiting for your feedback before merging it. Thanks.

**Comment by sachingarg2k1** [comment]
I tested this code on Windows 8.1 phone. VStudio refuses to register the package once I add this plugin. Error:
Error : DEP0001 : Unexpected Error: Package could not be registered. (Exception from HRESULT: 0x80073CF6)   CordovaApp.Phone

**Comment by brody2consult** [comment]
I wonder if you need to specify the capability in the manifest?

**Comment by Vo2le** [comment]
It seems you are right. After it worked i haven't thought about that. I testet it without the chat capability and it seems to work anyway. I will delete that lines.

I don't think this code will run on Windows 8 devices.

**Comment by brody2consult** [comment]
I just tested the version by @Vo2le on a new Windows 10 mobile device and it does start the SMS composition interface. (I have not tested the callbacks since I am not using it with a SIM right now.)

I recommend that you include this change and announce it in README.md so others can try it out.

**Comment by dbaq** [comment]
Thanks @brodybits and everybody else for testing this PR. Merging it. :+1: :beers:

**Pull request merged**
