### PR TITLE
#14 - Adding ability to create intent with multiple recipients

### PR DESCRIPTION
**Pull request by kentmw**

### CODE REVIEW

**Comment by brody2consult** [comment]
@kentmw your changes do not compile, need the following change to fix:

``` diff
--- a/src/android/Sms.java
+++ b/src/android/Sms.java
@@ -37,7 +37,7 @@ public class Sms extends CordovaPlugin {
                                                        // See http://stackoverflow.com/questions/18974898/send-sms-through-intent-to-multiple-phone-numbers/18975676#1
                                                        separator = ",";
                                                }
-                                               String phoneNumber = phoneNumbers.join(separator).replace("\"", "");
+                                               String phoneNumber = args.getJSONArray(0).join(separator).replace("\"", "");
                                                String message = args.getString(1);
                                                String method = args.getString(2);
                                                boolean replaceLineBreaks = Boolean.parseBoolean(args.getString(3));
```

**Comment by brody2consult** [comment]
@kentmw, please make this fix yourself and push it to your `master` to get this PR to compile and run. I tested your changes (with my fix) on my dual-SIM Motorola Moto G and sent the same message to both of my phone numbers (one Dutch, one US). My messaging app shows the same message sent to two numbers, single message in my messaging inbox.

**Comment by kentmw** [comment]
@brodybits, I pushed your fix, thanks for testing it! Do you need anything further from me on this for now?

**Comment by dbaq** [comment]
That looks good to me. Thanks for the contribution @kentmw and thanks for the review/test @brodybits.

If you have time @kentmw, that would be great to do the same thing without starting a new Intent.

**Pull request merged**
